### PR TITLE
Remove cypress

### PR DESCRIPTION
**Pull request by zolga**
Slows down package install

@vogre Please make sure I didn't forget any file - I followed your PR's change - Thanks!

### CODE REVIEW

**Review by vogre — APPROVED** [review]
Thanks! Looks like this gets all the references.

**Review by vogre — CHANGES_REQUESTED** [review]
Looks like `package-lock.json` was deleted whole, please re-run `npm install` and add it to be similar to the other projects.

**Comment by vogre** [comment]
PTAL at #5, I repeated PR from other repos into this one.

**Comment by zolga** [comment]
@vogre added the missing file, PTAL

**Comment by vogre** [comment]
Sorry, already merged #5 instead. This can be closed with 0 changes.

**Pull request closed without merging**
